name: recipe_management_app
description: A Flutter app for managing recipes - My Cookbook
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  provider: ^6.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  intl_utils: ^2.6.0

flutter:
  uses-material-design: true
  generate: true  # Enables flutter gen-l10n

  assets:
    - assets/images/veg1.jpg
    - assets/images/veg2.jpg
    - assets/images/veg3.jpg
    - assets/images/veg4.jpg
    - assets/images/veg5.jpg
    - assets/images/veg6.jpg
    - assets/images/veg7.jpg
    - assets/images/veg8.jpg
    - assets/images/nonveg1.jpg
    - assets/images/nonveg2.jpg
    - assets/images/nonveg3.jpg
    - assets/images/nonveg4.jpg
    - assets/images/nonveg5.jpg
    - assets/images/nonveg6.jpg
    - assets/images/nonveg7.jpg
    - assets/images/nonveg8.jpg
    - assets/images/chocolate_lava_cake.jpg
    - assets/images/tiramisu.jpg
    - assets/images/strawberry_shortcake.jpg
    - assets/images/lemon_meringue_pie.jpg
    - assets/images/dessert5.jpg
    - assets/images/dessert6.jpg
    - assets/images/dessert7.jpg
    - assets/images/dessert8.jpg
    - assets/images/icon.png

  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/TimesNewRoman.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations